apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  selector:
    role: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
